### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Ram-N** [gautamkrishnar/github-pages-gallery#11]
Hi @gautamkrishnar:

I like this idea, and found your project when searching for something simple for my needs.

A couple of small suggestions, if that would be okay.

1. At the very beginning on the README.md, please link to a couple of live gh-pages Galleries that are using this repo. Once we see what the end-result would be, we'd be much more inclined to go through the steps.
2. I'd also suggest an overview or Table of Contents at the top of README, so that we know what the steps are, esp. since there are over a dozen steps.
3. It was not clear to me why Travis CI was needed. Adding some explanation for what each component would do would help people like me in adopting your solution faster. 

I am giving these suggestions in the hopes that they are constructive and help many people use your project.

Regards,
Ram

**Comment by gautamkrishnar** [comment]
Hi @Ram-N thanks a lot for the suggestions.
