### ISSUE TITLE
image caption based on commit?

### ISSUE THREAD

**Issue by fogoat** [gautamkrishnar/github-pages-gallery#14]
Hi, very cool image gallery! I am wondering if there's a way to describe the images via a caption? I was thinking the commit title & description can be applied to the set of images uploaded? Just a thought. I'm not a programmer, so I'm sorry I can't contribute code, but thought it'd be a good idea.

**Comment by gautamkrishnar** [comment]
Hi @sunk818 this project doesn't handle the generation of the gallery we are just using the thumbs up https://github.com/thumbsup/thumbsup tool to generate the gallery. Please open an issue there instead if you have any doubts.
