### ISSUE TITLE
How to play GitHub Releases video ？

### ISSUE THREAD

**Issue by Pantyhose-X** [gautamkrishnar/github-pages-gallery#15]
GitHub releases Upload limit(2 GB)
[ me GitHub releases  video](https://github.com/Survivalwar/Pantyhose-X/releases)

How to set GitHub Releases  to play video on github blog

**Comment by gautamkrishnar** [comment]
You can use this template to upload videos as well. Fetching videos from the GitHub releases are beyond the scope of this project
