### ISSUE TITLE
No image gallery displayed, README.md is rendered instead

### ISSUE THREAD

**Issue by adrfantini** [gautamkrishnar/github-pages-gallery#2]
I am trying to build a small gallery site here:
[`https://adrfantini.github.io/image-gallery/`](https://adrfantini.github.io/image-gallery/)

Sources are here:
[`https://github.com/adrfantini/image-gallery`](https://github.com/adrfantini/image-gallery)

I setup Travis correctly and triple checked all the steps in [README.md](README.md). Unfortunately the result is that `gh-pages` builds the README.md and not the rendered image gallery.

It seems that a new branch `gh-pages` was generated; currently my GitHub Pages site is currently being built from the `master` branch, should I build it from the `gh-pages` branch? I tried, but nothing has changed apparently; maybe I should not have done this?

**Comment by gautamkrishnar** [comment]
@adrfantini looks like the build is working fine. You can see the html file generated here: https://github.com/adrfantini/image-gallery/blob/gh-pages/index.html

You must change the publishing branch of your repo (https://github.com/adrfantini/image-gallery) to gh-pages branch. 

Visit https://github.com/adrfantini/image-gallery/settings

Change the option *Source* to gh-pages branch:
<img width="874" alt="Screenshot 2019-04-13 at 5 49 20 PM" src="https://user-images.githubusercontent.com/8397274/56079593-81b52500-5e14-11e9-9d08-10e0f32e7e9c.png">

Please let me know if you are still facing any issues...

**Comment by gautamkrishnar** [comment]
I could've mentioned this in the readme... Just added it... Thanks a lot for reporting @adrfantini 👍

**Comment by adrfantini** [comment]
Works, thanks!
