### ISSUE TITLE
Is embed-exif: true working?  

### ISSUE THREAD

**Issue by Kay-S** [gautamkrishnar/github-pages-gallery#34]
Hi there,

I would like to embed the exif metadata for each image in my the gallery. I found embed-exif on the [thumbsup cheat sheet ](https://thumbsup.github.io/docs/3-configuration/cheat-sheet/), so I added it to my config.json like
`{
  "input": "./gallery",
  "output": "./build_output",
  "title": "Photo Gallery",
  "sort-albums-by": "title",
  "sort-media-by": "filename",
  "download-photos": "copy",
  "embed-exif": true,
  "cleanup": true,
  "theme": "cards",
  "css": "./custom.css",
  "footer": "This is a test",
  "usage-stats": false
}`
But it doesn't change anything. What am I doing wrong?

Best wishes

**Comment by gautamkrishnar** [comment]
@Kay-S  Please ask at https://github.com/thumbsup/thumbsup

This project is just a downstream of that tool.
