### ISSUE TITLE
Failed to deploy a GitHub action 

### ISSUE THREAD

**Issue by amblerkr** [gautamkrishnar/github-pages-gallery#38]
I use it often because it's easy and comfortable.
I already have one in use.

But today I wanted to create another one and it didn't work.
It keeps failing and I've been looking into what the problem is and this issue seems to be related. Can you take a look and fix it for me? 

https://github.com/actions/deploy-pages/issues/225

**Comment by gautamkrishnar** [comment]
@amblerkr this is not a bug, did u follow the instructions posted at step 4 here: https://github.com/gautamkrishnar/github-pages-gallery?tab=readme-ov-file#how-to-use

```
Click on the settings tab. Click on the Pages option under the Code and automation section. Make sure that you have the GitHub actions selected as the Source for the GitHub pages.
```
Once you enable that, simply upload a new image/video to re-trigger the deployment

**Comment by amblerkr** [comment]
![image](https://github.com/gautamkrishnar/github-pages-gallery/assets/67187038/112ca2e5-8945-4794-a82c-fa0b5a65059a)
The attached image is what I failed to do. I already have several running. It was weird, why did I make the same thing I did months ago and it didn't work? I tried several times. 

Of course! I set it up as a GitHub action. 
I solved the problem. 

**First, you need to upload your files.
Then you need to create your website first.**

**Then I need to set up the config.json and domain.**
