### ISSUE TITLE
can`t deploy page

### ISSUE THREAD

**Issue by Geekcrowds** [gautamkrishnar/github-pages-gallery#39]
can`t deploy page, got 404 issue

**Comment by Geekcrowds** [comment]
More details:


Run actions/deploy-pages@v3
Artifact exchange URL: https://pipelinesghubeus6.actions.githubusercontent.com/sSqDsd3y5j6o9quhd8fvm3VvJOb8AhKnY5naZUEf5jxW4vMDVv/_apis/pipelines/workflows/8120018005/artifacts?api-version=6.0-preview
Creating Pages deployment with payload:
{
	"artifact_url": "https://pipelinesghubeus6.actions.githubusercontent.com/sSqDsd3y5j6o9quhd8fvm3VvJOb8AhKnY5naZUEf5jxW4vMDVv/_apis/pipelines/1/runs/2/artifacts?artifactName=gh-pages&%24expand=SignedContent",
	"pages_build_version": "32ec376f12d20646e6771f3f831091a21d705f1a",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: Not Found
    at /home/runner/work/_actions/actions/deploy-pages/v3/node_modules/@octokit/request/dist-node/index.js:124:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v3/src/internal/api-client.js:126:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v3/src/internal/deployment.js:80:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v3/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 404) with build version 32ec376f12d20646e6771f3f831091a21d705f1a. Ensure GitHub Pages has been enabled: https://github.com/xxxxxxx/settings/pages

**Comment by gautamkrishnar** [comment]
@Geekcrowds as the error message says enable github pages. Check step 4 https://github.com/gautamkrishnar/github-pages-gallery?tab=readme-ov-file#how-to-use
