### ISSUE TITLE
Image move in the wrong direction

### ISSUE THREAD

**Issue by i-mat** [gautamkrishnar/github-pages-gallery#4]
This is the web I have built :
[https://pattonmt.github.io/life/Nature-Photo.html](url)
but when I click the right/left arrow at the edge of the image. The image move in the wrong direction.

The code are as follows:
[https://github.com/PattonMT/life](url)

**Comment by gautamkrishnar** [comment]
@PattonMT thanks for reporting. can you please open this issue on thunbsup repository https://github.com/thumbsup/thumbsup It is the issue with the static page generator. It will get automatically fixed when they release a fix.
