### ISSUE TITLE
Too many redirects when using cloudflare

### ISSUE THREAD

**Issue by F-alling** [gautamkrishnar/github-pages-gallery#40]
I try to load my gallery and it says "Too many redirects"
I looked and apparently the site is 301 redirecting to itself.
Site is hosted at https://kitty.falling.page
Headers below.
https://pastebin.com/ERfNngdw

Please let me know if this is something I did.
Thanks

**Comment by gautamkrishnar** [comment]
@F-alling a typical github pages pointing domain will look like the following:
```
> dig gkr.is-a.dev

; <<>> DiG 9.10.6 <<>> gkr.is-a.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45774
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;gkr.is-a.dev.			IN	A

;; ANSWER SECTION:
gkr.is-a.dev.		276	IN	CNAME	gautamkrishnar.github.io.
gautamkrishnar.github.io. 276	IN	A	185.199.109.153
gautamkrishnar.github.io. 276	IN	A	185.199.110.153
gautamkrishnar.github.io. 276	IN	A	185.199.108.153
gautamkrishnar.github.io. 276	IN	A	185.199.111.153

;; Query time: 2 msec
;; SERVER: 192.168.10.1#53(192.168.10.1)
;; WHEN: Tue Nov 12 07:01:46 IST 2024
;; MSG SIZE  rcvd: 132
```

But you's domain is not returning anything that is github.io check your DNS
```
> dig kitty.falling.page

; <<>> DiG 9.10.6 <<>> kitty.falling.page
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61063
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kitty.falling.page.		IN	A

;; ANSWER SECTION:
kitty.falling.page.	32	IN	A	172.67.139.88
kitty.falling.page.	32	IN	A	104.21.62.213

;; Query time: 3 msec
;; SERVER: 192.168.10.1#53(192.168.10.1)
;; WHEN: Tue Nov 12 07:03:27 IST 2024
;; MSG SIZE  rcvd: 68
```

**Comment by F-alling** [comment]
Thats odd in my cloudflare dashboard its properly setup?
![image](https://github.com/user-attachments/assets/232a6b28-1b23-476a-b2db-def077f13743)

**Comment by gautamkrishnar** [comment]
1. try using this github.io as CNAME. not A Record. Check https://community.cloudflare.com/t/setting-up-website-via-github-pages-cloudflare/299512/7
2. Double check if your https://github.com/F-alling/failing/blob/main/CNAME is correct also in your repo settings.

**Comment by F-alling** [comment]
cloudflare tells me I already have a cname record for this? im confused

**Comment by gautamkrishnar** [comment]
feel free to contact Cloudflare. Giving Cloudflare support is beyond the scope of this project.

**Comment by F-alling** [comment]
For anyone else having problems turns out having my SSL set to flexible in my cloudflare dashboard was causing issues.
