### ISSUE TITLE
Example gallery?

### ISSUE THREAD

**Issue by daviddoria** [gautamkrishnar/github-pages-gallery#7]
Did I miss a link to an example gallery in the readme? I'd love to play with it before following the whole procedure of setting up my own.

**Comment by daviddoria** [comment]
Ah, I just found https://photographernewbie.github.io/github-pages-gallery/ in one of the screenshots but it actually worked! I'd suggest putting that at the very top of the readme :)

**Comment by gautamkrishnar** [comment]
That's a great idea. Will add it soon. That was a test account i used to create the tutorial.
